const events = [
  {
    id: "freshman-orientation",
    date: "8/11/2025",
    title: "Freshman Orientation",
    category: "SBC Event",
    description: "Orientation programming for incoming freshmen.",
    location: "TBD",
  },
  {
    id: "picture-day",
    date: "8/20/2025, 8/21/2025, 8/22/2025",
    title: "Picture Day",
    category: "School Event",
    description: "School-wide student photo days.",
    location: "TBD",
  },
  {
    id: "welcome-back-rally",
    date: "8/22/2025",
    title: "Welcome Back Rally",
    category: "Spirit",
    description: "Welcome-back rally to kick off the school year.",
    location: "TBD",
  },
  {
    id: "club-registration-fall",
    date: "8/27/2025",
    title: "Club Registration",
    category: "Clubs",
    description: "Fall club registration window for organizations.",
    location: "TBD",
  },
  {
    id: "welcome-back-dance",
    date: "9/5/2025",
    title: "Welcome Back Dance",
    category: "Dance",
    description: "First major school dance of the year.",
    location: "TBD",
  },
  {
    id: "club-fair",
    date: "9/17/2025",
    title: "Club Fair",
    category: "Clubs",
    description: "Meet clubs, sign up, and connect with student leaders.",
    location: "TBD",
  },
  {
    id: "freshman-election-info-meeting",
    date: "9/19/2025, 9/24/2025",
    title: "Freshman Election Info Meeting",
    category: "Elections",
    description: "Information sessions for freshman election candidates.",
    location: "TBD",
  },
  {
    id: "late-night",
    date: "10/3/2025",
    title: "Late Night",
    category: "SBC Event",
    description: "Evening student event hosted by SBC.",
    location: "TBD",
  },
  {
    id: "fall-spirit-week",
    date: "10/6/2025-10/10/2025",
    title: "Fall 2025 Spirit Week",
    category: "Spirit",
    description: "Week-long spirit activities and class competitions.",
    location: "TBD",
  },
  {
    id: "beauty-and-the-beat-homecoming",
    date: "10/10/2025",
    title: "Beauty and the Beat Homecoming",
    category: "Dance",
    description: "Homecoming dance event.",
    location: "TBD",
  },
  {
    id: "principal-advisory-council-oct",
    date: "10/22/2025",
    title: "Principal Advisory Council",
    category: "Meeting",
    description: "Principal Advisory Council meeting.",
    location: "TBD",
  },
  {
    id: "haunted-house",
    date: "10/31/2025",
    title: "Haunted House",
    category: "SBC Event",
    description: "Halloween-themed school event.",
    location: "TBD",
  },
  {
    id: "fall-fest",
    date: "11/21/2025",
    title: "Fall Fest",
    category: "SBC Event",
    description: "Late-fall student celebration.",
    location: "TBD",
  },
  {
    id: "winterfaire",
    date: "12/19/2025",
    title: "Winterfaire",
    category: "SBC Event",
    description: "Winter student event and activities.",
    location: "TBD",
  },
  {
    id: "lowells-got-talent",
    date: "1/16/2026",
    title: "Lowell's Got Talent",
    category: "Performance",
    description: "Student talent showcase.",
    location: "TBD",
  },
  {
    id: "spring-club-registration",
    date: "1/21/2026",
    title: "Spring Club Registration",
    category: "Clubs",
    description: "Spring registration/check-in for clubs.",
    location: "TBD",
  },
  {
    id: "winterball-let-it-snow",
    date: "1/24/2026",
    title: "Winterball Let It Snow",
    category: "Dance",
    description: "Winterball dance event.",
    location: "TBD",
  },
  {
    id: "all-lsa-bakesale",
    date: "2/8/2026",
    title: "All LSA Bakesale",
    category: "Fundraiser",
    description: "LSA-wide bake sale fundraiser.",
    location: "TBD",
  },
  {
    id: "elections-commissioner-info-meeting",
    date: "2/10/2026",
    title: "Elections Commissioner Info Meeting",
    category: "Elections",
    description: "Info meeting for Elections Commissioner role.",
    location: "TBD",
  },
  {
    id: "bird-bash",
    date: "2/28/2026",
    title: "Bird Bash",
    category: "SBC Event",
    description: "School spirit event hosted by LSA/SBC.",
    location: "TBD",
  },
  {
    id: "spring-elections-info-meeting",
    date: "3/10/2026, 3/12/2026",
    title: "Spring Elections Info Meeting",
    category: "Elections",
    description: "Candidate info sessions for spring elections.",
    location: "TBD",
  },
  {
    id: "saw-week",
    date: "3/16/2026-3/20/2026",
    title: "Saw Week",
    category: "Spirit",
    description: "Multi-day spirit/event week programming.",
    location: "TBD",
  },
  {
    id: "principal-advisory-council-mar",
    date: "3/29/2026",
    title: "PAC Meeting",
    category: "Meeting",
    description: "Principal Advisory Council meeting.",
    location: "TBD",
  },
  {
    id: "cardinalympics",
    date: "4/13/2026-4/24/2026",
    title: "Cardinalympics",
    category: "Spirit",
    description: "Class competition series across events and activities.",
    location: "TBD",
  },
];

export default events;

